#!/bin/bash

# ###### Zona de Parámetros de solicitud de recursos a SLURM ############################
#
#SBATCH --job-name=FeO              #Nombre del job
#SBATCH -p short        #Cola a usar, Default=short (Ver colas y límites en /hpcfs/shared/README/partitions.txt)
#SBATCH -N 2            #Nodos requeridos, Default=1
#SBATCH --ntasks=24
#SBATCH --cpus-per-task=1               #Cores requeridos por task, recomendado para multi-thread, Default=1
#SBATCH --mem=49000              #Memoria en Mb por CPU, Default=2048
#SBATCH --time=24:30:00                 #Tiempo máximo de corrida, Default=2 horas
#SBATCH --mail-type=ALL
#SBATCH -o OUT                 #Nombre de archivo de salida
#
########################################################################################

# ################## Zona Carga de Módulos ############################################
module load quantum-espresso-cpu-mpi/7.2
#####################################################################################

# ###### Zona de Ejecución de código y comandos a ejecutar secuencialmente #############
mpirun --bind-to core -np 24 dos.x -i MnO.dos.in > MnO.dos.out 
########################################################################################

